# vim:ft=ansible:


- name: Inital Setup
  hosts: all
  sudo: yes
  vars:
    # Admin users to create
    genericusers_users:
      - name: jason
        ssh_keys:
          - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        system: yes
        groups: [admin, staff, sudo]
        shell: /bin/bash
    # Additional utility packagesto be installed by ANXS.utilities role
    utilities_extras:
      - vim
      - git
  roles:
    - jason.mcvetta.sudoers-forwarded-ssh
    - jason.mcvetta.debian-upgrade-reboot
    - ANXS.hostname
    - ANXS.generic-users
    - ANXS.utilities
    - geerlingguy.security
    - geerlingguy.firewall
  tasks:
    - name: Ensure sudo group can use sudo without password
      lineinfile: 
        dest: /etc/sudoers 
        state: present 
        regexp: '^%sudo' 
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
  tags:
    - initial

- hosts: all
  sudo: yes
  tasks:
  
    - name: Ensure Ansible PPA is added
      apt_repository:
        repo: "ppa:ansible/ansible"

    - name: Ensure Ansible is installed
      apt:
        name: ansible

    - name: Ensure ~jason/.gitconfig is present
      copy:
        src: ~/.gitconfig
        dest: ~jason/.gitconfig
        owner: jason

    - name: Ensure ~jason/.bashrc contains "set -o vi"
      lineinfile:
        dest: ~jason/.bashrc
        line: set -o vi

    - name: Ensure jmcvetta/ubuntu-packages .deb is present
      get_url:
        url: https://github.com/jmcvetta/ubuntu-packages/raw/master/jmcvetta-workstation_1.28_all.deb
        dest: /tmp/jmcvetta.deb

    - name: Ensure jmcvetta/ubuntu-packages is installed
      command: dpkg -i /tmp/jmcvetta.deb
      ignore_errors: yes

    - name: Ensure jmcvetta/ubuntu-packages dependencies are installed
      command: apt-get install -fy

